<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog Post 4 –– Incumbency Advantage | A minimal Hugo website</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    
  </head>

  <body>
    <nav>
    <ul class="menu">
      
      <li><a href="/">Home</a></li>
      
      <li><a href="/about/">About</a></li>
      
      <li><a href="/categories/">Categories</a></li>
      
      <li><a href="/tags/">Tags</a></li>
      
      <li><a href="/index.xml">Subscribe</a></li>
      
    </ul>
    <hr/>
    </nav>

<div class="article-meta">
<h1><span class="title">Blog Post 4 –– Incumbency Advantage</span></h1>
<h2 class="author">Chris S</h2>
<h2 class="date">2024/09/29</h2>
</div>

<main>
<pre><code>## # A tibble: 97 × 14
##     year quarter   GDP GDP_growth_quarterly  RDPI RDPI_growth_quarterly   CPI
##    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;                &lt;dbl&gt; &lt;dbl&gt;                 &lt;dbl&gt; &lt;dbl&gt;
##  1  1928       2    NA                   NA    NA                    NA    NA
##  2  1929       2    NA                   NA    NA                    NA    NA
##  3  1930       2    NA                   NA    NA                    NA    NA
##  4  1931       2    NA                   NA    NA                    NA    NA
##  5  1932       2    NA                   NA    NA                    NA    NA
##  6  1933       2    NA                   NA    NA                    NA    NA
##  7  1934       2    NA                   NA    NA                    NA    NA
##  8  1935       2    NA                   NA    NA                    NA    NA
##  9  1936       2    NA                   NA    NA                    NA    NA
## 10  1937       2    NA                   NA    NA                    NA    NA
## # ℹ 87 more rows
## # ℹ 7 more variables: unemployment &lt;dbl&gt;, sp500_open &lt;dbl&gt;, sp500_high &lt;dbl&gt;,
## #   sp500_low &lt;dbl&gt;, sp500_close &lt;dbl&gt;, sp500_adj_close &lt;dbl&gt;,
## #   sp500_volume &lt;dbl&gt;
</code></pre>
<p><em>This blog is an ongoing assignment for Gov 1347: Election Analytics, a course at Harvard College taught by Professor <a href="https://www.ryandenos.com/">Ryan Enos</a>. It will be updated weekly and culminate in a predictive model of the 2024 presidential election.</em></p>
<h2 id="introduction----how-should-we-treat-the-incumbency-advantage-in-our-2024-electoral-forecasts">Introduction &ndash; How should we treat the <em>incumbency advantage</em> in our 2024 electoral forecasts?</h2>
<p>Humans are predictable creatures. For example, if you choose a seat to sit in on the first day of lecture, chances are, you&rsquo;ll choose the same spot next week. And the week after that &ndash; probably until the last day of class. Is this the same for voting behavior? When it comes to elections, incumbents seem to hold a similar seat-saving advantage. Voters often stick with the familiar, and the incumbency advantage becomes a powerful force in shaping election outcomes. But is this advantage truly as reliable as picking the same lecture seat, or is it more complicated?</p>
<p>Moreover, when existing presidents do a poor job at handling national concerns such as social upheaval or economic downturn, they leave a sour taste in the public&rsquo;s memory. Perhaps this tarnished reputation lingers, making voters more inclined to seek change rather than continuity &ndash; just as how a coffee spill might make you choose a new lecture seat&hellip;</p>
<p>As usual, to analyze these questions, we&rsquo;ll start with the data. So, let&rsquo;s dive in!</p>
<h2 id="war-and-incumbency">War and Incumbency</h2>
<p>War is an unbelievably challenging time for most countries. It is in these pivotal moments when we look towards our leaders to navigate this environment with strength, decisiveness, and humility. Therefore, taking data between 1948 and 2024, I&rsquo;ve produced the following summary for incumbency re-election:</p>
<pre><code>##   reelect_president  N Percent
## 1             FALSE 12   66.67
## 2              TRUE  6   33.33
</code></pre>
<p>We can immediately notice something &ndash; in 12/18 post-war elections, the incumbent president did not win re-election, meaning that voters opted for change rather than continuing with the same president. Historically, the incumbent advantage seems to be weaker than what&rsquo;s often assumed, which may be due to several factors. For example, many of these incumbents faced significant fundamental economic crises, including Carter&rsquo;s era of inflation and Bush&rsquo;s period of recession. In doing so, voters may often seek fresh leadership if the current administration fails to address these national concerns effectively in the public&rsquo;s eye.</p>
<p>Of course, we also have to consider potential outliers &ndash; such as Kennedy&rsquo;s close victory in 1960 or the Watergate scandal that impacted Ford&rsquo;s chances in 1976 &ndash; that may have contributed to surprisingly low re-election rate.</p>
<p>However, the analysis above represents overall incumbency re-election. Let&rsquo;s see how it changes when the incumbent <strong>actually runs</strong> for re-election:</p>
<pre><code>## Elections with At Least One Incumbent Running: 11
## Incumbent Victories: 7
## Percentage: 63.64
</code></pre>
<p>The data shows a slightly higher success rate (63.64%) when the incumbents choose to run for re-election. Under standard assumptions, we can see that these candidates benefit from increased name recognition, established campaign infrastructure, and the ability to leverage their position to shape public perception (e.g., by delivering policies or showing leadership in crises).</p>
<p>Let&rsquo;s zoom in even closer and look at the six elections since 2000:</p>
<pre><code>## # A tibble: 3 × 7
##    year candidate_DEM    candidate_REP    incumbent_DEM incumbent_REP winner_DEM
##   &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;            &lt;lgl&gt;         &lt;lgl&gt;         &lt;lgl&gt;     
## 1  2004 Kerry, John      Bush, George W.  FALSE         TRUE          FALSE     
## 2  2012 Obama, Barack H. Romney, Mitt     TRUE          FALSE         TRUE      
## 3  2020 Biden, Joseph R. Trump, Donald J. FALSE         TRUE          TRUE      
## # ℹ 1 more variable: winner_REP &lt;lgl&gt;
</code></pre>
<p>The table above details the each of the specific candidates running in the past 3 elections. We see that 2/3 elections were won by incumbents seeking re-election (Bush in 2004 and Obama in 2012), which mathematically checks out roughly with our previous 63% calculation. More importantly, the 2020 election breaks the previous pattern of incumbency advantage, showing that a sitting president is still vulnerable, especially under critical circumstances including a national health crisis and economic upheaval.</p>
<h2 id="candidate-vs-party-incumbency">Candidate vs Party Incumbency</h2>
<p>Instead of focusing solely on the candidates running for re-election, let&rsquo;s examine how the party incumbency performs during these situations:</p>
<pre><code>##   reelect_party  N Percent
## 1         FALSE 10   55.56
## 2          TRUE  8   44.44
</code></pre>
<p>From above, we can see that 55.56% of the time, the party that held the presidency <strong>did not</strong> win the next election. Surprisingly, this suggests that the party in power is slightly more likely to <strong>lose the presidency</strong> than retain it. A big factor we&rsquo;re seeing here is party fatigue &ndash; a phenomenon in which voters will often desire change if a party has been in power for multiple terms, particularly if it has faced challenges and controversies. This can be further amplified when a former president is very popular and the party fails to secure an impressive successor, which can be seen in the 1992 election after Reagan. Another simple example could be in 2016, in which Obama&rsquo;s two terms of success could not sustain the democratic party, and a general voter desire for change led to Trump&rsquo;s presidency.</p>
<p>There are also economic and political components in play, such as in 1980 when the Democrats controlled the presidency but Carter&rsquo;s disastrous handling of inflation and the Iran Hostage Crisis led to a republican victory by Reagan. Similarly, Trump&rsquo;s failed leadership during the COVID-19 pandemic further led to a loss in party confidence by voters, leading to an eventually transition to Biden and the democrats.</p>
<p>Overall, the near-even split between party retention and loss highlights the competitive and unpredictable nature of presidential elections, making our forecasting job more challenging and exciting!</p>
<h2 id="im-in-power----now-what">I&rsquo;m In Power &ndash; Now What?</h2>
<pre><code class="language-r">d_pork_state |&gt; 
  filter(!is.na(state_year_type)) |&gt; 
  group_by(state_year_type) |&gt;
  summarize(mean_grant = mean(grant_mil, na.rm = T), se_grant = sd(grant_mil, na.rm = T)/sqrt(n())) |&gt; 
  ggplot(aes(x = state_year_type, y = mean_grant, ymin = mean_grant-1.96*se_grant, ymax = mean_grant+1.96*se_grant)) + 
  coord_flip() + 
  geom_bar(stat = &quot;identity&quot;, fill = &quot;chartreuse4&quot;) + 
  geom_errorbar(width = 0.2) + 
  labs(x = &quot;Type of State &amp; Year&quot;, 
       y = &quot;Federal Grant Spending (Millions of $)&quot;, 
       title = &quot;Federal Grant Spending (Millions $) by State Election Type&quot;) + 
  theme_minimal() + 
  theme(plot.title = element_text(size = 20),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12))
</code></pre>
<img src="https://example.org/post/2024/09/29/blog-post-4-incumbency-advantage/index_files/figure-html/unnamed-chunk-7-1.png" width="672" />
<pre><code class="language-r">d_pork_state |&gt; 
  filter(!is.na(state_year_type2)) |&gt; 
  group_by(state_year_type2) |&gt;
  summarize(mean_grant = mean(grant_mil, na.rm = T), se_grant = sd(grant_mil, na.rm = T)/sqrt(n())) |&gt; 
  ggplot(aes(x = state_year_type2, y = mean_grant, ymin = mean_grant-1.96*se_grant, ymax = mean_grant+1.96*se_grant)) + 
  coord_flip() + 
  geom_bar(stat = &quot;identity&quot;, fill = &quot;chartreuse4&quot;) + 
  geom_errorbar(width = 0.2) + 
  labs(x = &quot;Type of State &amp; Year&quot;, 
       y = &quot;Federal Grant Spending (Millions of $)&quot;, 
       title = &quot;Federal Grant Spending (Millions $) by State Election Type&quot;) + 
  theme_minimal() +
  theme(plot.title = element_text(size = 20),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12))
</code></pre>
<img src="https://example.org/post/2024/09/29/blog-post-4-incumbency-advantage/index_files/figure-html/unnamed-chunk-8-1.png" width="672" />
<h1 id="county-model">county model</h1>
<pre><code class="language-r">pork_mod_county_1 &lt;- lm(dvoteswing_inc  ~ dpct_grants*comp_state + as.factor(year), 
                      d_pork_county)
summary(pork_mod_county_1)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = dvoteswing_inc ~ dpct_grants * comp_state + as.factor(year), 
##     data = d_pork_county)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -27.7179  -2.8547  -0.0047   2.7889  23.2187 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            -6.450079   0.084452 -76.376  &lt; 2e-16 ***
## dpct_grants             0.004762   0.001036   4.595 4.35e-06 ***
## comp_state              0.152687   0.076143   2.005 0.044949 *  
## as.factor(year)1992     0.170688   0.115787   1.474 0.140458    
## as.factor(year)1996     6.345396   0.115509  54.934  &lt; 2e-16 ***
## as.factor(year)2000    -2.049544   0.116215 -17.636  &lt; 2e-16 ***
## as.factor(year)2004     8.407388   0.115576  72.743  &lt; 2e-16 ***
## as.factor(year)2008     3.136792   0.116122  27.013  &lt; 2e-16 ***
## dpct_grants:comp_state  0.006391   0.001764   3.623 0.000292 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.495 on 18455 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.4027,	Adjusted R-squared:  0.4025 
## F-statistic:  1556 on 8 and 18455 DF,  p-value: &lt; 2.2e-16
</code></pre>
<pre><code class="language-r">pork_mod_county_2 &lt;- lm(dvoteswing_inc ~ dpct_grants*comp_state + as.factor(year) +
                          dpc_income + inc_ad_diff + inc_campaign_diff + 
                          dhousevote_inc + iraq_cas2004 + iraq_cas2008 + 
                          dpct_popl,
                        data = d_pork_county)
summary(pork_mod_county_2)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = dvoteswing_inc ~ dpct_grants * comp_state + as.factor(year) + 
##     dpc_income + inc_ad_diff + inc_campaign_diff + dhousevote_inc + 
##     iraq_cas2004 + iraq_cas2008 + dpct_popl, data = d_pork_county)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -27.321  -2.848  -0.025   2.728  22.994 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            -6.523210   0.084963 -76.777  &lt; 2e-16 ***
## dpct_grants             0.003954   0.001043   3.792 0.000150 ***
## comp_state              0.155418   0.077223   2.013 0.044173 *  
## as.factor(year)1992    -0.156389   0.120591  -1.297 0.194699    
## as.factor(year)1996     6.230500   0.119533  52.124  &lt; 2e-16 ***
## as.factor(year)2000    -2.000293   0.118588 -16.868  &lt; 2e-16 ***
## as.factor(year)2004     8.248378   0.119371  69.099  &lt; 2e-16 ***
## as.factor(year)2008     3.574248   0.124060  28.811  &lt; 2e-16 ***
## dpc_income              0.134285   0.022326   6.015 1.84e-09 ***
## inc_ad_diff             0.061345   0.010851   5.654 1.60e-08 ***
## inc_campaign_diff       0.161845   0.013166  12.292  &lt; 2e-16 ***
## dhousevote_inc          0.012093   0.001952   6.196 5.91e-10 ***
## iraq_cas2004           -0.153092   0.069585  -2.200 0.027816 *  
## iraq_cas2008           -0.164783   0.021677  -7.602 3.07e-14 ***
## dpct_popl               2.103344   0.530292   3.966 7.33e-05 ***
## dpct_grants:comp_state  0.006411   0.001781   3.600 0.000319 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.452 on 17943 degrees of freedom
##   (506 observations deleted due to missingness)
## Multiple R-squared:  0.4199,	Adjusted R-squared:  0.4194 
## F-statistic: 865.9 on 15 and 17943 DF,  p-value: &lt; 2.2e-16
</code></pre>
<h1 id="pork-state-model">pork state model</h1>
<pre><code class="language-r">d_pork_state_model &lt;- d_state_vote |&gt;
  mutate(state_abb = state.abb[match(d_state_vote$state, state.name)]) |&gt;
  inner_join(d_pork_state, by = c(&quot;year&quot;, &quot;state_abb&quot;)) |&gt;
  left_join(d_vote, by = &quot;year&quot;) |&gt;
  filter(incumbent_party == TRUE) |&gt;
  mutate(inc_pv2p = ifelse(party == &quot;REP&quot;, R_pv2p, D_pv2p)) |&gt;
  mutate(is_comp = case_when(state_year_type == &quot;swing + election year&quot; ~ 1,
                             .default = 0)) |&gt;
  group_by(state) |&gt;
  mutate(change_grant_mil = (1-grant_mil/(lag(grant_mil, n = 1)))*100,
         change_inc_pv2p = (1-inc_pv2p/(lag(inc_pv2p, n = 1)))*100) |&gt;
  ungroup() |&gt;
  select(state, year, is_comp, change_grant_mil, change_inc_pv2p)
</code></pre>
<pre><code>## Warning in left_join(inner_join(mutate(d_state_vote, state_abb = state.abb[match(d_state_vote$state, : Detected an unexpected many-to-many relationship between `x` and `y`.
## ℹ Row 1 of `x` matches multiple rows in `y`.
## ℹ Row 19 of `y` matches multiple rows in `x`.
## ℹ If a many-to-many relationship is expected, set `relationship =
##   &quot;many-to-many&quot;` to silence this warning.
</code></pre>
<pre><code class="language-r">pork_state_mod &lt;- lm(change_inc_pv2p ~ is_comp*change_grant_mil + as.factor(year),
                     data = d_pork_state_model)
summary(pork_state_mod)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = change_inc_pv2p ~ is_comp * change_grant_mil + as.factor(year), 
##     data = d_pork_state_model)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -136.740   -6.628    0.341    7.176   64.748 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                9.6346     3.6317   2.653  0.00842 ** 
## is_comp                   -0.4004     4.1498  -0.096  0.92319    
## change_grant_mil           0.1138     0.1051   1.082  0.28001    
## as.factor(year)1992        6.8952     6.7168   1.027  0.30548    
## as.factor(year)1996      -21.3789     5.2732  -4.054 6.46e-05 ***
## as.factor(year)2000        3.5773     5.6260   0.636  0.52537    
## as.factor(year)2004      -30.1619     5.4753  -5.509 7.96e-08 ***
## as.factor(year)2008        1.0850     4.8627   0.223  0.82360    
## is_comp:change_grant_mil  -0.1027     0.1643  -0.625  0.53246    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 23.43 on 291 degrees of freedom
##   (50 observations deleted due to missingness)
## Multiple R-squared:  0.2675,	Adjusted R-squared:  0.2474 
## F-statistic: 13.29 on 8 and 291 DF,  p-value: 2.299e-16
</code></pre>
<h1 id="time-for-a-change-model">time for a change model</h1>
<pre><code class="language-r">d_tfc_train &lt;- d_vote |&gt; 
  left_join(d_econ, by = &quot;year&quot;) |&gt; 
  filter(incumbent_party) |&gt;
  mutate(incumbent = as.numeric(incumbent))
</code></pre>
<pre><code>## Warning in left_join(d_vote, d_econ, by = &quot;year&quot;): Detected an unexpected many-to-many relationship between `x` and `y`.
## ℹ Row 1 of `x` matches multiple rows in `y`.
## ℹ Row 82 of `y` matches multiple rows in `x`.
## ℹ If a many-to-many relationship is expected, set `relationship =
##   &quot;many-to-many&quot;` to silence this warning.
</code></pre>
<pre><code class="language-r"># estimate through 2016
tfc_mod_2016 &lt;- lm(pv2p ~ GDP_growth_quarterly + incumbent + juneapp, 
                   data = subset(d_tfc_train, year &lt; 2020))
summary(tfc_mod_2016)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = pv2p ~ GDP_growth_quarterly + incumbent + juneapp, 
##     data = subset(d_tfc_train, year &lt; 2020))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.3398 -2.4193  0.0809  1.3467  6.3340 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          49.33341    0.58816  83.877  &lt; 2e-16 ***
## GDP_growth_quarterly  0.15374    0.09177   1.675  0.09845 .  
## incumbent             2.09521    0.71428   2.933  0.00457 ** 
## juneapp               0.14966    0.01391  10.756 2.55e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.835 on 68 degrees of freedom
## Multiple R-squared:  0.7106,	Adjusted R-squared:  0.6978 
## F-statistic: 55.65 on 3 and 68 DF,  p-value: &lt; 2.2e-16
</code></pre>
<pre><code class="language-r"># estimate for 2020
tfc_mod_2020 &lt;- lm(pv2p ~ juneapp, 
                   data = subset(d_tfc_train, year &lt; 2024))
summary(tfc_mod_2020)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = pv2p ~ juneapp, data = subset(d_tfc_train, year &lt; 
##     2024))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.0627 -2.0250 -0.1604  1.8038  6.9681 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 51.02572    0.34522  147.81   &lt;2e-16 ***
## juneapp      0.16501    0.01351   12.22   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.961 on 74 degrees of freedom
## Multiple R-squared:  0.6685,	Adjusted R-squared:  0.664 
## F-statistic: 149.2 on 1 and 74 DF,  p-value: &lt; 2.2e-16
</code></pre>

</main>

  <footer>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/katex/dist/katex.min.css">
<script src="//cdn.jsdelivr.net/combine/npm/katex/dist/katex.min.js,npm/katex/dist/contrib/auto-render.min.js,npm/@xiee/utils/js/render-katex.js" defer></script>

<script src="//cdn.jsdelivr.net/npm/@xiee/utils/js/center-img.min.js" defer></script>

  
  <hr/>
  © <a href="https://yihui.org">Yihui Xie</a> 2017 &ndash; 2024 | <a href="https://github.com/yihui">Github</a> | <a href="https://twitter.com/xieyihui">Twitter</a>
  
  </footer>
  </body>
</html>

