<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog Post 3 –– Polling and Prediction | A minimal Hugo website</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    
  </head>

  <body>
    <nav>
    <ul class="menu">
      
      <li><a href="/">Home</a></li>
      
      <li><a href="/about/">About</a></li>
      
      <li><a href="/categories/">Categories</a></li>
      
      <li><a href="/tags/">Tags</a></li>
      
      <li><a href="/index.xml">Subscribe</a></li>
      
    </ul>
    <hr/>
    </nav>

<div class="article-meta">
<h1><span class="title">Blog Post 3 –– Polling and Prediction</span></h1>
<h2 class="author">Chris S</h2>
<h2 class="date">2024/09/22</h2>
</div>

<main>
<p><em>This blog is an ongoing assignment for Gov 1347: Election Analytics, a course at Harvard College taught by Professor <a href="https://www.ryandenos.com/">Ryan Enos</a>. It will be updated weekly and culminate in a predictive model of the 2024 presidential election.</em></p>
<h2 id="introduction----how-can-we-best-use-polls-to-predict-election-outcomes">Introduction &ndash; How can we best use <em>polls</em> to predict <em>election outcomes?</em></h2>
<p>What&rsquo;s the first thing you hear when you flick on news channels covering any election? <strong>Polls</strong>. We&rsquo;ve done hundreds of them ourselves in our lifetime, from restaurant surveys to product reviews and presidential candidates. These quick little quizzes help provide <strong>direct insights</strong> from the public about various issues, including voting behavior, candidate favorability, and more. Generally speaking, they serve as feedback loops, allowing parties and campaigns to <strong>adjust their strategies</strong> based on how the public responds during an election cycle. Breaking these statistics down by demographic categories allows these candidates to further tailor their messaging to specific audiences.</p>
<p>However, there are common pitfalls related to polling, including <strong>sampling bias, nonresponse bias, timing, and more</strong>. It&rsquo;s our job to figure out what matters and what doesn&rsquo;t. More importantly, <strong>can we use them to help predict election outcomes</strong>, or will they simply lead us astray? Let&rsquo;s dive in!</p>
<h2 id="2020-and-2024-polling----a-detailed-analysis">2020 and 2024 Polling &ndash; A Detailed Analysis</h2>
<img src="https://example.org/post/2024/09/22/blog-post-3-polling/index_files/figure-html/unnamed-chunk-2-1.png" width="672" />
<p>Immediately, we can notice some interesting trends. First, before COVID-19 hit, both democratic and republican <strong>polling averages were roughly stable</strong>. However, once COVID-19 was in full swing, we saw a significant decline in Republican approval, likely due to the <strong>public&rsquo;s perception of how Trump was handling the pandemic</strong>, on both healthcare and economic fronts. With George Floyd&rsquo;s death, we see a further decline in Republican approval, especially in handling <strong>racial injustice and social upheaval</strong>. Both the RNC and DNCs showed a bump in approval allowing parties to get in front of viewers, increase media coverage, and <strong>consolidate support</strong>.</p>
<img src="https://example.org/post/2024/09/22/blog-post-3-polling/index_files/figure-html/unnamed-chunk-3-1.png" width="672" />
<p>Looking at 2024 polling averages, we see a <strong>general candidate disapproval trend for both parties</strong>. Particularly for the Biden administration, the democratic party was struggling to gain ground as the November election quickly approached. The sharp increase we observed for the democrats in July has to do largely with <strong>Biden&rsquo;s decision to drop out of the race and endorse Kamala Harris</strong> as the democratic presidential candidate. Moreover, her strong performance in the recent debate proved her capabilities as a leader and her vision for the future which many Americans seemed to resonate with, <strong>skyrocketing average polling approval past Trump</strong>.</p>
<p>Altogether, we can see the influence of major political, social, and health-related events on candidate approval, which can be captured by polling averages. Now the question is, do these polling behaviors provide any predictive power? Let&rsquo;s find out!</p>
<h2 id="polls-and-predictions----how-about-november">Polls and Predictions &ndash; How about November?</h2>
<p>Before we look into 2024, let&rsquo;s examine how powerful November polling averages were at predicting election outcomes for the democratic party in 2020:</p>
<pre><code>## 
## Call:
## lm(formula = pv2p ~ nov_poll, data = subset(d_poll_nov, party == 
##     &quot;DEM&quot;))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.0155 -2.4353 -0.3752  1.4026  5.8014 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  14.2936     7.1693   1.994 0.069416 .  
## nov_poll      0.7856     0.1608   4.885 0.000376 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.968 on 12 degrees of freedom
## Multiple R-squared:  0.6654,	Adjusted R-squared:  0.6375 
## F-statistic: 23.86 on 1 and 12 DF,  p-value: 0.0003756
</code></pre>
<p>There are a few critical results to note about the model above. First, the coefficient for <strong>nov_poll (0.7856)</strong> means that for each 1-point increase in November polling support, the predicted vote share increases by 0.79. Moreover, the <strong>p-value is extremely small (0.000376)</strong>, indicating that the <strong>nov_poll</strong> variable is a statistically significant predictor of pv2p. What&rsquo;s more impressive is the multiple R-squared value of <strong>0.66554</strong> (closer to 1 is better), showing us that the model provides <strong>a reasonably good fit and reliability</strong>. In the context of the 2020 election results, we can see that polling support in November was a strong indicator of electoral success. Due to its proximity to election day, November polls can <strong>capture the most recent public opinion</strong>, particularly since voters will have likely made up their minds by now. As we&rsquo;ve seen before, major campaign events have great influences on voter support and approval, and as the election nears, there are simply fewer of these so opinions are less volatile.</p>
<p>Instead of focusing solely on the democratic party, let&rsquo;s widen our scope to all parties in the dataset in the following model:</p>
<pre><code>## 
## Call:
## lm(formula = pv2p ~ nov_poll, data = d_poll_nov)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.6190 -1.6523 -0.5808  1.3629  6.0220 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 17.92577    4.15543   4.314 0.000205 ***
## nov_poll     0.70787    0.09099   7.780 2.97e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.75 on 26 degrees of freedom
## Multiple R-squared:  0.6995,	Adjusted R-squared:  0.6879 
## F-statistic: 60.52 on 1 and 26 DF,  p-value: 2.974e-08
</code></pre>
<p>Similar to our previous model, we see that the <strong>nov_poll coefficient (0.70787)</strong> means that for each 1-point increase in November polling support, the predicted vote share increases by roughly 0.71 points. The positive relationship indicates that higher polling support in November is <strong>strongly associated with higher vote share</strong>. Once again, we see that the p-value is extremely low, reinforcing the <strong>statistical significance of November&rsquo;s reliability as an indicator</strong>. A strong <strong>0.7 R-squared value</strong> also provides confidence that the model is robust and captures the data effectively. More importantly, this model confirms that November polls are a strong predictor of election outcomes, <strong>regardless of party affiliation</strong>.</p>
<h2 id="the-power-of-weeks-regularization-methods">The Power of Weeks? Regularization Methods</h2>
<p>Instead of looking just at November results, let&rsquo;s examine how our model performs when we consider weekly polling averages. Of course, we run into an <strong>alarming issue &ndash; multicollinearity</strong>. This occurs when we have several variables in our model that are highly correlated, producing a potentially skewed view of our results. To handle this, we&rsquo;ll use <strong>ridge regression</strong>, which introduces a <em>penalty term</em> to the least squares cost function, preventing the coefficient from <strong>becoming too large</strong>, and helping to adjust the multicollinearity factor.</p>
<p>Let&rsquo;s examine our results:</p>
<pre><code>## 
## Call:
## lm(formula = paste0(&quot;pv2p ~ &quot;, paste0(&quot;poll_weeks_left_&quot;, 0:30, 
##     collapse = &quot; + &quot;)), data = d_poll_weeks_train)
## 
## Residuals:
## ALL 28 residuals are 0: no residual degrees of freedom!
## 
## Coefficients: (4 not defined because of singularities)
##                    Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)        28.25534        NaN     NaN      NaN
## poll_weeks_left_0   3.24113        NaN     NaN      NaN
## poll_weeks_left_1   0.02516        NaN     NaN      NaN
## poll_weeks_left_2  -8.87360        NaN     NaN      NaN
## poll_weeks_left_3   7.91455        NaN     NaN      NaN
## poll_weeks_left_4   0.74573        NaN     NaN      NaN
## poll_weeks_left_5   1.41567        NaN     NaN      NaN
## poll_weeks_left_6  -4.58444        NaN     NaN      NaN
## poll_weeks_left_7   4.63361        NaN     NaN      NaN
## poll_weeks_left_8  -0.95121        NaN     NaN      NaN
## poll_weeks_left_9  -1.55307        NaN     NaN      NaN
## poll_weeks_left_10 -1.38062        NaN     NaN      NaN
## poll_weeks_left_11  1.74881        NaN     NaN      NaN
## poll_weeks_left_12 -1.28871        NaN     NaN      NaN
## poll_weeks_left_13 -0.08482        NaN     NaN      NaN
## poll_weeks_left_14  0.87498        NaN     NaN      NaN
## poll_weeks_left_15 -0.16310        NaN     NaN      NaN
## poll_weeks_left_16 -0.34501        NaN     NaN      NaN
## poll_weeks_left_17 -0.38689        NaN     NaN      NaN
## poll_weeks_left_18 -0.06281        NaN     NaN      NaN
## poll_weeks_left_19 -0.17204        NaN     NaN      NaN
## poll_weeks_left_20  1.52230        NaN     NaN      NaN
## poll_weeks_left_21 -0.72487        NaN     NaN      NaN
## poll_weeks_left_22 -2.76531        NaN     NaN      NaN
## poll_weeks_left_23  4.90361        NaN     NaN      NaN
## poll_weeks_left_24 -2.04431        NaN     NaN      NaN
## poll_weeks_left_25 -0.76078        NaN     NaN      NaN
## poll_weeks_left_26 -0.47860        NaN     NaN      NaN
## poll_weeks_left_27       NA         NA      NA       NA
## poll_weeks_left_28       NA         NA      NA       NA
## poll_weeks_left_29       NA         NA      NA       NA
## poll_weeks_left_30       NA         NA      NA       NA
## 
## Residual standard error: NaN on 0 degrees of freedom
## Multiple R-squared:      1,	Adjusted R-squared:    NaN 
## F-statistic:   NaN on 27 and 0 DF,  p-value: NA
</code></pre>
<p>The model shows that we have no residual degrees of freedom, meaning we have <strong>perfect multicollinearity</strong>, which happens when there is an exact linear dependence among the predictors &ndash; in this case, weekly polling averages. The <strong>R-squared value is 1.0</strong>, indicating a perfect fit, but this is misleading since this fit is not due to the model&rsquo;s inherent capabilities, but rather from overfitting caused by too many correlated predictors.</p>
<p>To better understand what we&rsquo;re doing, let&rsquo;s visualize our ridge regression:</p>
<img src="https://example.org/post/2024/09/22/blog-post-3-polling/index_files/figure-html/unnamed-chunk-8-1.png" width="672" />
<p>We can clearly see <strong>lambda</strong> acting as the regularization parameter here, adding <strong>more penalty to the coefficients</strong> and shrinking them <strong>towards zero</strong> to fight the multicollinearity and overfitting. This <strong>prevents any single variable from dominating the model</strong>, which is particularly important when dealing with models containing lots of correlated variables. Of course, there are many other regularization methods, including <em>Lasso and Elastic Net</em>, each with its own attributes.</p>
<p>For the purposes of this blog, we will dive straight into a comparison between all three and draw conclusions, instead of an in-depth examination of each method:</p>
<img src="https://example.org/post/2024/09/22/blog-post-3-polling/index_files/figure-html/unnamed-chunk-9-1.png" width="672" />
<p>By visualizing the four methods above, we see how OLS coefficients are <strong>larger compared to the regularized methods</strong>, which suggests strong <strong>overfitting</strong>, particularly in the presence of multicollinearity. Lasso and Ridge perform reasonably well, but <strong>Elastic Net performs the best</strong>, striking a balance between model complexity and highlighting key predictor variables.</p>
<p>Now that we have our chosen method, let&rsquo;s what the model tells us about the 2024 election results:</p>
<pre><code>##            s1
## [1,] 51.79268
## [2,] 50.65879
</code></pre>
<p>Our current polling model predicts that Harris will win the results indicate that <strong>Harris will win the vote share by a very slim margin</strong>. Assuming that our historical data is representative of current dynamics and changes to voting behavior, the Elastic-net method helps handle multicollinearity and provides a <strong>balance between shrinkage and variable elimination</strong>. Further sensitivity testing should be used to get a <strong>better understanding of the reliability of its predictions</strong>.</p>
<h2 id="a-battle-of-two-pollsters">A Battle of Two Pollsters</h2>
<p>To extend our knowledge of polling, let&rsquo;s take a look at <strong>two different approaches</strong>. <a href="https://www.natesilver.net/p/model-methodology-2024">Silver&rsquo;s</a> methodology takes on a more <strong>conservative approach</strong>, by keeping his model largely unchanged from 2020, with a few specific updates, such as COVID. Generally, the model continues to <strong>rely heavily on historical election data</strong> and assumes that voter behavior will remain consistent with a <em>high degree of continuity</em>. This helps reinforce the model&rsquo;s stability and reduces the risk of overfitting to recent events or anomalies.</p>
<p>In contrast, <a href="https://abcnews.go.com/538/538s-2024-presidential-election-forecast-works/story?id=110867585">Morris</a> takes on a far more <strong>nuanced view of the 2024 model</strong>, completely rebuilding it and incorporating a <strong>more holistic integration of polling and fundamentals</strong>, such as the economy. His model combines historical voting patterns with demographic data and geographic proximity. By using fundamental indicators, like GDP growth, employment, and political factors (incumbency, presidential approval ratings) he can support a more <strong>dynamic relationship between variables in his model</strong>. His use of extensive correlation matrices also helps project state-level polling movement and adds to the <strong>flexibility and responsiveness of the model</strong>.</p>
<p>Overall, I prefer <strong>538&rsquo;s model</strong> as it integrates a wide range of indicators to produce a <strong>more nuanced and comprehensive understanding of the electoral dynamics at play</strong>. Especially considering an election with so many changes and polarization, these fluctuations will be important factors to consider when building a model. This holistic approach of combining fundamentals and historical election data helps to handle uncertainty and <strong>provide a more robust prediction of the election</strong>. Further, its ability to update in <strong>real-time</strong> with new polling and fundamental data allows viewers to observe the most current state of the race. Most importantly, he accounts for polling errors and state similarities which can provide a <strong>balanced view that adapts to recent trends without extensive overfitting</strong>.</p>
<h2 id="data-sources">Data Sources:</h2>
<p>Data are from the GOV 1347 course materials. All files can be found <a href="https://github.com/cys9772/election-blog4">here</a>. All external sources are hyperlinked.</p>

</main>

  <footer>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/katex/dist/katex.min.css">
<script src="//cdn.jsdelivr.net/combine/npm/katex/dist/katex.min.js,npm/katex/dist/contrib/auto-render.min.js,npm/@xiee/utils/js/render-katex.js" defer></script>

<script src="//cdn.jsdelivr.net/npm/@xiee/utils/js/center-img.min.js" defer></script>

  
  <hr/>
  © <a href="https://yihui.org">Yihui Xie</a> 2017 &ndash; 2024 | <a href="https://github.com/yihui">Github</a> | <a href="https://twitter.com/xieyihui">Twitter</a>
  
  </footer>
  </body>
</html>

