---
title: A Look Into Alabama
author: Chris S
date: '2024-12-10'
slug: a-look-into-alabama
categories: []
tags: []
---

*This blog is an ongoing assignment for Gov 1347: Election Analytics, a course at Harvard College taught by Professor [Ryan Enos](https://www.ryandenos.com/). It will be updated weekly and culminate in a predictive model of the 2024 presidential election.*

## Introduction -- Rolling hills and deep Southern traditions. How did Alabama shake up our forecast and what can we learn?

Another election cycle has come and gone, and with it, the endless stream of campaign ads, polling updates, and debates that had us glued to our screens. But now, it’s time to answer our state-specific investigation into Alabama. Did it follow the national script? Why or why not? More importantly, how did economic signals, demographic trends, and the occasional surprise moments, impact Alabama's results compared to our model's expectations. 

Our model suggested a solid outcome for the Republican candidate in this historically red state, yet we uncovered some discrepancies worth exploring. How well did the forecast align with the final vote share? Were there unexpected swings in key counties or differences in turnout among demographic groups?

Let’s dive into the geography, history, and campaigns that shaped Alabama’s election narrative in 2024 -- and uncover what it all tells us about modeling, forecasting, and the ever-elusive nature of political prediction (something that Professor Enos has highlighted throughout the course).

## A Brief Look Into Alabama's Electoral History

Alabama, known as the "Heart of Dixie," is located in the southeastern United States, bordered by Tennessee to the north, Georgia to the east, Florida and the Gulf of Mexico to the south, and Mississippi to the west. Its geography includes the Appalachian Mountains in the north, the fertile Black Belt region in the central area, and coastal plains in the south.

According to data from the 2020 U.S. Census, Alabama has a population of approximately 5 million people, with a racial composition was about 69% White, 27% Black or African American, with the remaining percentage comprising other races and ethnicities. In particular, the Black Belt region, named for its rich, dark soil, has a significant African American population and has historically been a focal point for civil rights activities.

In the 2024 elections, Alabama's down-ballot races included contests for the U.S. House of Representatives, state judicial positions, and local offices. Most notably, in 2023 the state's congressional map underwent redistricting following a Supreme Court ruling (*Allen v. Milligan*) that mandated the creation of a second district with a substantial Black population to ensure fair representation. However, the new proposed revisions did not full y comply with the Court's directive, as they failed to establish a second majority-Black district. Consequently, a federal court intervened, appointing a special master to develop a compliant map, leading to a competitive race in the newly redrawn 2nd Congressional District, which now has a voting-age population that is 49% Black. 

In terms of voting trends, Alabama has been a Republican stronghold in presidential elections. The state has consistently voted for the Republican presidential candidate since 1980. In the previous 2020 election, Donald Trump secured 62% of the vote, while Joe Biden received 37%. Thus, the results we observed in this year's 2024 election are rather unsurprising for Alabama. More will be discussed below.

## Forecasted Outcome and Results

In the 2024 Presidential Election, we witnessed how Alabama maintained its longstanding Republican alignment, with former President Donald Trump securing the state's nine electoral votes. As stated before, the pre-election forecasts consistently predicted this outcome, highlighting Alabama's historical voting patterns.

In general, analysis done in class and from various political forecasting organizations uniformly categorized Alabama as a "Safe Republican" state. More specifically, the Cook Political Report, Inside Elections, and Sabato's Crystal Ball all rated Alabama as solidly Republican in their 2024 electoral projections. 

According to the Alabama Secretary of State's official election results, Donald Trump received 64.8% of the state's vote, while Vice President Kamala Harris garnered 34.5%. This 30.3-percentage-point margin closely aligns with the 2020 election, where Trump led by approximately 25.5 points. 

Thus, the actual election results in Alabama were consistent with both quantitative and qualitative forecasts. The substantial lead predicted for the Republican candidate closely matched expectations from previous years. Alabama represents just a small alignment in the greater partisan tendencies and calcification for certain states.

## A Nuanced Campaign in Alabama:

In this year's election cycle, Alabama's political landscape was marked by a predictable presidential race and a notably competitive congressional contest, particularly in the newly redrawn 2nd Congressional District.

In terms of campaign activity, Trump's campaign presence in Alabama was highlighted by his attendance at the University of Alabama vs. University of Georgia football game in Tuscaloosa on September 28, 2024. More importantly, this appearance allowed him to engage with supporters in a non-traditional campaign setting, where he was greeted with chants of "USA" and interacted with fans. His campaign work in Alabama has deep roots, stretching back almost a year, when Trump headlined the Alabama Republican Party's Summer Dinner in Montgomery, attracting roughly 3000 attendees and raising over $1 million in support.

On the other hand, Harris focused her campaign efforts on more competitive battleground states, resulting in minimal direct engagement in Alabama. She did have some local support, particularly in July of 2024, when Alabama democratic delegates rallied behind her candidacy, emphasizing her qualifications and decisive leadership. More specifically, state senator Kirk Hatcher highlighted the importance of unification and representative Juandalynn Givan praised her ability to rally Black female voters. Ultimately, however, she aligned closely with findings from *Darr and Levendusky (2014)*, in which campaigns typically concentrate field offices and resources where they can maximize electoral gains, leading to minimal Alabama efforts. 

As mentioned before, a significant development in Alabama's 2024 election cycle was the redrawing of the 2nd Congressional District. This redistricting set the stage for a competitive race between Democrat Shomari Figures, a former aide to U.S. Attorney General Merrick Garland, and Republican Caroleene Dobson. In particular, both candidates engaged in passionate debates on abortion, immigration, and the economy. Figures emphasized his political experience and commitment to infrastructure, education, and healthcare, while Dobson criticized Figures as a "Washington insider" and positioned herself as an advocate for working families. 

High-profile endorsements also played a key role in the campaign dynamics. Former U.S. Attorney General Eric Holder, who supported the litigation leading to the redistricting, appeared with Figures at campaign events, underscoring the election's historical significance and urging voters to support advancement in equality and justice. 

In the end, Figures won the election for the redrawn 2nd Congressional District, marking a significant shift from its previous Republican representation and providing Alabama with its second Black representative in Congress. 

Throughout the 2024 election cycle, national and local outlets highlighted the potential impact on representation and the broader significance for voting rights. The congressional race in the 2nd District saw increased voter interest and participation due to its competitiveness and the historical context of the redistricting. Surprisingly, in contrast, the presidential race experienced lower voter turnout, consistent with Alabama's pattern of low participation in non-competitive races. 

Thus, while the presidential campaign in Alabama followed expected patterns with limited direct engagement, the congressional race in the redrawn 2nd District introduced a dynamic and competitive element to the state's 2024 election cycle, drawing significant attention from candidates, media, and voters alike.

## Final Thoughts...

Given Alabama's strong Republican inclination, the absence of a robust Democratic ground game in Alabama may have contributed to lower Democratic voter mobilization and turnout, impacting Harris's overall vote share.

Trump's local engagement at a high-profile college football game in Tuscalosa provided him with substantial media coverage and direct engagement with Alabama voters. Such appearances can enhance a candidate's visibility and favorability among voters as it allows for direction personal engagement, humanizing them and making them seem more approachable in general. These engagements can also energize the current voting base, generating support for areas and field offices that have become less active. In contrast, Harris's limited presence in the state may have resulted in reduced voter enthusiasm and support.

Alabama's electorate has consistently favored Republican candidates in presidential elections. In class, we discussed how Achen and Bartels (2017) argue that voters often exhibit strong partisan loyalties, making them less susceptible to campaign efforts. To be honest, this entrenched Republican allegiance likely led to a higher vote share for Trump, regardless of campaign activities from either party. In addition, they provide evidence that voters adjust their policy views and information perception to align with their partsan affiliations, reinforcing existing biases and reducing possibilities for shifting partisan loyalty.

Thus, while the competitive race in Alabama's newly redrawn 2nd Congressional District may have influenced voter turnout and preferences, its impact on the presidential vote share was likely minimal given historical and current voting trend data.

Besides the possible flaws in my model discussed in my final reflection [here](https://cys9772.github.io/election-blog4/post/2024/11/17/final-reflection/), I'd also highlight *Gelman and King (1993)* which emphasizes that while polls can be volatile, actual votes are more predictable based on historical patterns. While Alabama likely did not influence my overall model accuracy, I'm excited to take what I've learned and investigate more battleground states, in which the model may have overestimated voter behavior along polls rather than partisan history and fundamentals.

## References:

\begin{enumerate}
    \item Achen, Christopher H., and Larry M. Bartels. \textit{Democracy for Realists: Why Elections Do Not Produce Responsive Government}. Princeton University Press, 2017.
    \item ``Alabama Presidential Forecast.'' \textit{The Hill}, 5 Nov. 2024, \url{https://elections2024.thehill.com/forecast/2024/president/alabama/}. Accessed 10 Dec. 2024.
    \item Alabama Secretary of State. ``Alabama Votes | Alabama Secretary of State.'' \textit{Alabamavotes.gov}, 2024, \url{https://www2.alabamavotes.gov/electionNight/statewideResultsByContest.aspx?ecode=1001225}. Accessed 10 Dec. 2024.
    \item Chandler, Kim. ``Former US Attorney General Says House Candidate Shomari Figures in Alabama Will Fight for Equality.'' \textit{AP News}, 29 Oct. 2024, \url{https://apnews.com/article/eric-holder-shomari-figures-alabama-house-a88c25a8569bb4c07eb9b2cd0f28edec}. Accessed 10 Dec. 2024.
    \item Chandler, Kim, and Safiyah Riddle. ``Figures and Dobson Trade Jabs in Testy Debate, Here Are the Key Takeaways.'' \textit{AP News}, 10 Oct. 2024, \url{https://apnews.com/article/alabama-2nd-congressional-district-candidates-debate-6f648731c31287e4093799b9c6a11c0}. Accessed 10 Dec. 2024.
    \item Chapoco, Ralph. ``Alabama Certifies Election Results; Secretary of State Says New Laws Didn't Affect Turnout.'' \textit{Rocketcitynow.com, WZDX}, 26 Nov. 2024, \url{https://www.rocketcitynow.com/article/news/state/alabama-certifies-election-results-secretary-state-new-laws-voters/525-024347e5-fb2f-4c38-8ced-fedfce8e4be3}. Accessed 10 Dec. 2024.
    \item Darr, Joshua P., and Matthew S. Levendusky. ``Relying on the Ground Game: The Placement and Effect of Campaign Field Offices.'' \textit{American Politics Research}, vol. 42, no. 3, 2014, pp. 529–548.
    \item Donlevy, Katherine. ``Trump Greeted by Chants of `USA,' Tosses Popcorn to Fans as He Attends Alabama vs. Georgia Football Game.'' \textit{New York Post}, 29 Sept. 2024, \url{https://nypost.com/2024/09/28/us-news/president-trump-arrives-at-bryant-denny-stadium-in-tuscaloosa-for-alabama-vs-georgia-football-game/}. Accessed 10 Dec. 2024.
    \item Gelman, Andrew, and Gary King. ``Why Are American Presidential Election Campaign Polls So Variable When Votes Are So Predictable?'' \textit{British Journal of Political Science}, vol. 23, no. 4, 1993, pp. 409–451.
    \item Hall, Ryan. ``New Alabama Law Expands Mental Health Treatment for Substance Use Disorders.'' \textit{CBS 42}, 22 July 2024, \url{https://doi.org/1089550527}. Accessed 10 Dec. 2024.
    \item ``Presidential Election in Alabama, 2020.'' \textit{Ballotpedia}, 2020, \url{https://ballotpedia.org/Presidential_election_in_Alabama%2C_2020}. Accessed 10 Dec. 2024.
    \item Sweedler, Maya. ``What to Expect in Alabama on Election Day.'' \textit{AP News}, 25 Oct. 2024, \url{https://apnews.com/article/alabama-election-decision-notes-president-house-ced8b51b7056d44b874fdabf12a326e33}. Accessed 10 Dec. 2024.
\end{enumerate}



## Data Sources:

Data are from the GOV 1347 course materials. All files can be found [here](https://github.com/cys9772/election-blog4). All external sources are hyperlinked.


