<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog Post 2 -- Elections and the Economy | A minimal Hugo website</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    
  </head>

  <body>
    <nav>
    <ul class="menu">
      
      <li><a href="/">Home</a></li>
      
      <li><a href="/about/">About</a></li>
      
      <li><a href="/categories/">Categories</a></li>
      
      <li><a href="/tags/">Tags</a></li>
      
      <li><a href="/index.xml">Subscribe</a></li>
      
    </ul>
    <hr/>
    </nav>

<div class="article-meta">
<h1><span class="title">Blog Post 2 &ndash; Elections and the Economy</span></h1>
<h2 class="author">Chris S</h2>
<h2 class="date">2024/09/15</h2>
</div>

<main>
<p><em>This blog is an ongoing assignment for Gov 1347: Election Analytics, a course at Harvard College taught by Professor <a href="https://www.ryandenos.com/">Ryan Enos</a>. It will be updated weekly and culminate in a predictive model of the 2024 presidential election.</em></p>
<h2 id="introduction----can-we-predict-election-outcomes-using-only-the-state-of-the-economy-if-so-how-well">Introduction &ndash; Can we predict election outcomes using <em>only</em> the state of the economy? If so, how well?</h2>
<p>In our previous blog, we established some fundamental understanding and visualizations regarding vote share and geographic distributions. Now, we begin examining how fundamental variables influence elections &ndash; <strong>namely, the economy</strong>. Political and data scientists have commented on the economy&rsquo;s ability to <strong>influence elections and election forecasts</strong>. For example, if the economy were the experience modest growth, the equations predicted that the Republican candidate would likely win the election <a href="https://fairmodel.econ.yale.edu/RAYFAIR/PDF/2018B.htm">(Fair 2018)</a>. Additional research also showed that the state of the economy has a non-negligible ability to mobilize and persuade voters. <a href="https://hollis.harvard.edu/primo-explore/fulldisplay?docid=TN_cdi_jstor_books_j_ctt7ztpn1&amp;context=PC&amp;vid=HVD2&amp;search_scope=everything&amp;tab=everything&amp;lang=en_US">(Sides and Vavreck 2013)</a>.</p>
<p>All in all, the economy clearly has <em>some</em> impact on voter behavior and predicting election outcomes. How much or how little is a trickier question. Hopefully this blog will illuminate further aspects and allow us to improve our models down the road. Let&rsquo;s take a closer look!</p>
<h2 id="2020-or-not">2020 Or Not?</h2>
<p>One of the first measurements of economic growth and performance is <strong>quarterly GDP growth</strong>. Within this value reflects many important factors including <em>consumer spending, business investment, and government activity</em>, which are key indicators for economic health. Under an election-prediction lens, positive trends benefit incumbents as voters may credit them with economic stability and vice versa. I&rsquo;ve created a <strong>bivariate regression</strong> below to examine the relationship between second quarter GDP growth and two-party vote share:</p>
<pre><code>## 
## Call:
## lm(formula = pv2p ~ GDP_growth_quarterly, data = d_inc_econ)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.7666 -3.3847 -0.7697  2.9121  8.8809 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           51.2580     1.1399  44.968   &lt;2e-16 ***
## GDP_growth_quarterly   0.2739     0.1380   1.985   0.0636 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.834 on 17 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.1881,	Adjusted R-squared:  0.1403 
## F-statistic: 3.938 on 1 and 17 DF,  p-value: 0.06358
</code></pre>
<img src="https://example.org/post/2024/09/15/blog-post-2/index_files/figure-html/unnamed-chunk-3-1.png" width="672" />
<p>There are a few important things to notice. Overall, there seems to be some slight <strong>positive relationship</strong> between second-quarter GDP growth and the incumbent party’s share of the popular vote. Specifically, as GDP growth increases, the incumbent party tends to receive a higher vote share. However, the shading around the regression line reveals a fair amount of uncertainty in the prediction, especially for lower levels of GDP growth. From our summary statistics panel, we also see that the coefficient for GDP growth has a <strong>p-value of 0.0636</strong>, which is above the standard 0.05 threshold for statistical significance. This means there is some evidence of a relationship between GDP growth and vote share, but it’s not statistically significant, indicating that while economic conditions matter, there may be other factors at play. The <strong>low R-squared value of 0.1881</strong> and <strong>high residual standard error of 4.834</strong> suggest that economic performance alone is not powerful enough to capture elections and voter behavior.</p>
<p>We can also observe that 2020 represents a significant outlier, with a much lower vote share than the model predicts based on GDP growth alone. This is evidence that external factors, including public health crises like COVID-19 can play a major role in an election, even overriding the typical relationship we observe between economic performance and electoral success. It&rsquo;s possible that many voters focused on how the incumbent handled the public health event, placing less emphaisis on other fundamental indicators like GDP.</p>
<p>Let&rsquo;s take a look and see what our model would look like with <strong>2020 removed</strong>:</p>
<pre><code>## 
## Call:
## lm(formula = pv2p ~ GDP_growth_quarterly, data = d_inc_econ_2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.237 -4.160  0.450  1.904  8.728 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           49.3751     1.4163  34.862   &lt;2e-16 ***
## GDP_growth_quarterly   0.7366     0.2655   2.774   0.0135 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.463 on 16 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.3248,	Adjusted R-squared:  0.2826 
## F-statistic: 7.697 on 1 and 16 DF,  p-value: 0.01354
</code></pre>
<img src="https://example.org/post/2024/09/15/blog-post-2/index_files/figure-html/unnamed-chunk-4-1.png" width="672" />
<p>Besides the similar trends previously observed, with the 2020 data point removed, the R-squared value alone <strong>(0.3248)</strong> already shows us that the model fits the data better. The shading around the regression line is narrower, indicating a <strong>more consistent relationship</strong> between GDP growth and vote share. The p-value for GDP growth is now <strong>0.0135</strong>, which is below the 0.05 threshold and therefore statistically significant. In general, we can see how much of an outlier 2020 was. Compared to before, it likely pulled down the slope and increased the uncertainty, as the incumbent party&rsquo;s vote share was much lower than expected based on GDP growth.</p>
<p>A correlation calculation further supports the observations above. The first value is with 2020 and the second value is without.</p>
<p>Table: <span id="tab:unnamed-chunk-5"></span>Table 1: Correlation between GDP Growth and Incumbent Vote Share</p>
<table>
<thead>
<tr>
<th style="text-align:left">Model</th>
<th style="text-align:right">Correlation</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">With 2020</td>
<td style="text-align:right">NA</td>
</tr>
<tr>
<td style="text-align:left">Without 2020</td>
<td style="text-align:right">NA</td>
</tr>
</tbody>
</table>
<h2 id="gdp-dpi-and-both">GDP, DPI, and Both</h2>
<p>As an extension to our models, let&rsquo;s examine other economic factors and provide side-by-side comparisons of each to discover prediction outcomes and sensitivity robustness. For our purposes, we will use <strong>disposable personal income (DPI)</strong> as our independent variable. Similar to GDP, research has found that voters who experience a rise in disposable income are more likely to support the incumbent, whereas those experiencing a decline might vote for the opposition <a href="https://www.cambridge.org/core/journals/american-political-science-review/article/digging-into-the-pocketbook-evidence-on-economic-voting-from-income-registry-data-matched-to-a-voter-survey/7FF7E7FFFDCA634B79D2289C6880CF3D">(Healy 2017)</a>. As DPI increases, voters may feel more economically secure, <strong>which can result in greater support for the incumbent party</strong>. However, nuances and changes related to income inequality can play significant roles in how voters perceive DPI and their voting behavior as candidates explore redistribution initiatives <a href="https://link.springer.com/article/10.1057/s41295-021-00249-2">(Zivkovic 2021)</a>.</p>
<p>To investigate this further, I created 3 models based on 3 different factors &ndash; GDP, DPI, and GDP + DPI. Below we can see a comparison between their R-squared values, AIC (Akaike Information Criterion), and BIC (Bayesian Information Criterion).</p>
<pre><code>## # A tibble: 3 × 5
##   model           r.squared adj.r.squared   AIC   BIC
##   &lt;chr&gt;               &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 GDP Model          0.188        0.140    118.  121.
## 2 DPI Model          0.0638       0.00875  120.  123.
## 3 GDP + DPI Model    0.193        0.0922   120.  123.
</code></pre>
<p>At first glance, we can see that the the addition of DPI to GDP does not greatly increase the R-squared value (<strong>increased from 0.1881 to 0.193</strong>0), which is possibly due to <strong>multi-co linearity</strong>, in which GDP and DPI are both highly related to one another and can be seen as redundant. However, when DPI was used on its own, we see a sharp drop in the R-squared value, indicating that DPI does not provide a strong explanation for voter behavior and election outcomes. Of course, we have to keep in mind that this is <strong>with the 2020 data point included</strong>, which we&rsquo;ve already observed to have weakening impact on our models from before.</p>
<p>Now that we have 3 models, we can predict the vote share for 2024 and compare them side-by-side:</p>
<p>Table: <span id="tab:unnamed-chunk-7"></span>Table 2: Predicted Vote Share for 2024 based on Different Models</p>
<table>
<thead>
<tr>
<th style="text-align:left">Model</th>
<th style="text-align:right">Predicted_Vote_Share</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">GDP Model</td>
<td style="text-align:right">52.07966</td>
</tr>
<tr>
<td style="text-align:left">DPI Model</td>
<td style="text-align:right">51.98460</td>
</tr>
<tr>
<td style="text-align:left">GDP + DPI Model</td>
<td style="text-align:right">52.11903</td>
</tr>
</tbody>
</table>
<p>Unsurprisingly, there is <strong>little difference</strong> between the three models on their predictions, with the DPI-only model predicting the lowest vote share. More importantly, let&rsquo;s test each model&rsquo;s sensitivity to changes in measurement for GDP, DPI, and the economy as a whole. First, let&rsquo;s do a <strong>cross-validation test</strong>, in which we hold hold out some years and train the model on the remaining data:</p>
<pre><code>## Out-of-sample error for GDP Model:  -1.443742
</code></pre>
<pre><code>## Out-of-sample error for DPI Model:  -1.458842
</code></pre>
<pre><code>## Out-of-sample error for GDP + DPI Model:  -1.242682
</code></pre>
<p>The model has <strong>similar out-of-sample errors</strong> for GDP and DPI, which indicates that both provide roughly comparable predictive power for our data. The best seems to be the combination of GDP + DPI, which while not perfect, suggest that the models are <strong>reasonably good</strong> at predicting election outcomes based on our economic data.</p>
<p>We can also visualize each model&rsquo;s performance below based on changes in economic measures to see how sensitive it is:</p>
<img src="https://example.org/post/2024/09/15/blog-post-2/index_files/figure-html/unnamed-chunk-9-1.png" width="672" />
<p>Both red (GDP + DPI) and blue (GDP only) show <strong>relative stability in their predictions</strong> and a reasonable increase in incumbent party vote share with each respective increase in quarterly GDP growth. However, we can see that the DPI-only model <strong>struggles significantly</strong> to produce a meaningful prediction as economic measures change. This makes logical sense as we consider the extremely low R-squared value we previously found.</p>
<h2 id="now-what">Now What?</h2>
<p>Overall, we&rsquo;ve understood how fundamental economic factors influence election outcomes and voter behavior. Literature has shown a relationship between the two, highlight how strong economic performance tends to favor the party in power, while economic downturns can jeopardize their chances. However, this relationship <strong>isn&rsquo;t an end-all-be-all</strong> as our data and models show relatively <strong>low correlation and R-squared values</strong>. Further, economic factors like DPI seemed to perform worse compared to standard models at fitting and predicting future election outcomes. All in all, this exploration has showed that the economy does have <strong>some influence</strong> on voter behavior and excites me to add additional non-economic variables to improve my model, such as demographic data, media/advertising, and policy initiatives.</p>
<p>Also, with 2020 being such an outlier, is it even worth keeping in our models&hellip;? Stay tuned!</p>
<h2 id="data-sources">Data Sources:</h2>
<p>Data are from the GOV 1347 course materials. All files can be found <a href="https://github.com/cys9772/election-blog4">here</a>. All external sources are hyperlinked.</p>

</main>

  <footer>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/katex/dist/katex.min.css">
<script src="//cdn.jsdelivr.net/combine/npm/katex/dist/katex.min.js,npm/katex/dist/contrib/auto-render.min.js,npm/@xiee/utils/js/render-katex.js" defer></script>

<script src="//cdn.jsdelivr.net/npm/@xiee/utils/js/center-img.min.js" defer></script>

  
  <hr/>
  © <a href="https://yihui.org">Yihui Xie</a> 2017 &ndash; 2024 | <a href="https://github.com/yihui">Github</a> | <a href="https://twitter.com/xieyihui">Twitter</a>
  
  </footer>
  </body>
</html>

